<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Snapshot.Protocol/Snapshot.Protocol.csproj" />
    <ProjectReference Include="../../src/Snapshot.Processing/Snapshot.Processing.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
</Project>
