<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../client/src/snapshot-protocol.js" Link="wwwroot/snapshot-protocol.js" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
